export type GameLanguage = 'en' | 'it';

export const WORD_LISTS: Record<GameLanguage, Record<number, string[]>> = {
  en: {
    4: ['HACK', 'CODE', 'DATA', 'LOCK', 'OPEN', 'PASS', 'SAFE', 'TERM', 'BYTE', 'DISK', 'FILE', 'GATE', 'NODE', 'PORT', 'ROOT', 'SYNC', 'VOID', 'ZERO'],
    5: ['ADMIN', 'AGENT', 'ALPHA', 'BASIC', 'CACHE', 'CLOUD', 'CRASH', 'DEBUG', 'DELTA', 'EMAIL', 'ENTRY', 'ERROR', 'FIELD', 'FINAL', 'FORCE', 'FRAME', 'GHOST', 'GRANT', 'INPUT', 'LOGIC'],
    6: ['ACCESS', 'BINARY', 'BUFFER', 'CIPHER', 'CLIENT', 'COOKIE', 'DECODE', 'DEFEND', 'DOMAIN', 'ENABLE', 'ENCODE', 'ENGINE', 'EXPORT', 'FILTER', 'FORMAT', 'GATHER', 'GLOBAL', 'HIDDEN', 'IMPORT', 'KERNEL'],
    7: ['ACCOUNT', 'ADDRESS', 'ADVANCE', 'ARCHIVE', 'BACKEND', 'BALANCE', 'BROWSER', 'CAPTURE', 'CHANNEL', 'CLUSTER', 'COMMAND', 'CONNECT', 'CONSOLE', 'CONTROL', 'COUNTER', 'DEFAULT', 'DESKTOP', 'DISPLAY', 'DYNAMIC', 'EXECUTE'],
    8: ['ABSTRACT', 'BACKDOOR', 'CHECKSUM', 'COMPILER', 'DATABASE', 'DOWNLOAD', 'EMULATOR', 'ENCRYPT', 'FIREWALL', 'FUNCTION', 'GRAPHICS', 'HARDWARE', 'INTERNET', 'KEYBOARD', 'LANGUAGE', 'LOCATION', 'MACHINE', 'METADATA', 'MONITOR', 'NETWORK'],
    9: ['ALGORITHM', 'BOOTSTRAP', 'BROADCAST', 'COMPONENT', 'DIRECTORY', 'DOCUMENT', 'EXECUTION', 'FRAMEWORK', 'GATEWAY', 'INTERFACE', 'JAVASCRIPT', 'MAINFRAME', 'OPERATION', 'PARAMETER', 'PERMISSION', 'PROCESSOR', 'PROTOCOL', 'RESOURCES', 'SECURITY', 'SUBSYSTEM'],
    10: ['BACKGROUND', 'CONNECTION', 'DEPLOYMENT', 'ENCRYPTION', 'EXPRESSION', 'FOUNDATION', 'IMPLEMENT', 'INTEGRATION', 'MANAGEMENT', 'MONITORING', 'PERMISSION', 'PROCESSING', 'PRODUCTION', 'PROTECTION', 'REPOSITORY', 'RESOLUTION', 'STATISTICS', 'TECHNOLOGY', 'TERMINATOR', 'VALIDATION'],
    11: ['APPLICATION', 'ARCHITECTURE', 'AUTHENTICATION', 'CONFIGURATION', 'DEVELOPMENT', 'ENVIRONMENT', 'INFORMATION', 'INSTALLATION', 'MAINTENANCE', 'PERFORMANCE', 'PROGRAMMING', 'TRANSACTION', 'TRANSMISSION', 'UTILIZATION', 'VERIFICATION'],
    12: ['ADMINISTRATION', 'COMMUNICATION', 'IMPLEMENTATION', 'INFRASTRUCTURE', 'ORGANIZATION', 'REGISTRATION', 'REQUIREMENTS', 'SPECIFICATION', 'SUBSCRIPTION', 'TRANSMISSION', 'VERIFICATION'],
  },
  it: {
    4: ['APRI', 'ARTE', 'CAOS', 'CODA', 'DATI', 'DISC', 'FILE', 'LUCE', 'NODO', 'ONDA', 'PACE', 'RETE', 'RISO', 'SOLO', 'VERO', 'VINO', 'VOCE', 'ZERO', 'ZONA', 'PORT'],
    5: ['AVVIO', 'BLOCC', 'CAMPO', 'CARTA', 'CRASH', 'DEBUG', 'EMAIL', 'ERROR', 'FALSO', 'GIOCO', 'LATTE', 'LIBRO', 'LOGIC', 'MONDO', 'NOTTE', 'PONTE', 'SCALA', 'TEMPO', 'TERRA', 'TESTA', 'TIGRE', 'VALLE', 'VIRUS', 'VOLTO', 'DELTA', 'FIELD', 'FRAME', 'GRANT', 'INPUT', 'FINAL'],
    6: ['ACCESS', 'BINARY', 'BUFFER', 'CIPHER', 'CLIENT', 'CODICE', 'COOKIE', 'DATORE', 'DECODE', 'DEFEND', 'DOMAIN', 'ENABLE', 'ENCODE', 'ENGINE', 'EXPORT', 'FILTER', 'FORMAT', 'GESTOR', 'GLOBAL', 'HIDDEN', 'IMPORT', 'KERNEL', 'MEMORI', 'PAROLE', 'VALORE'],
    7: ['COMANDO', 'CONSOLE', 'CONTROL', 'DEFAULT', 'DESKTOP', 'DISPLAY', 'INTERNO', 'MONITOR', 'PROGRAM', 'SISTEMA', 'TERMINA', 'ACCOUNT', 'ADDRESS', 'ARCHIVE', 'BALANCE', 'BROWSER', 'CAPTURE', 'CHANNEL', 'CLUSTER', 'CONNECT'],
    8: ['ARCHIVIO', 'COMPILER', 'DATABASE', 'DOWNLOAD', 'EMULATO', 'FIREWALL', 'FUNCTION', 'GRAPHICS', 'HARDWARE', 'INTERNET', 'KEYBOARD', 'LANGUAGE', 'LOCATION', 'MACHINE', 'METADATA', 'MONITOR', 'NETWORK', 'ABSTRACT', 'CHECKSUM', 'ENCRYPT'],
    9: ['ALGORITMO', 'COMPONENT', 'DIRECTORY', 'DOCUMENT', 'FRAMEWORK', 'GATEWAY', 'INTERFACE', 'MAINFRAME', 'OPERATION', 'PARAMETER', 'PERMISSION', 'PROCESSOR', 'PROTOCOL', 'RESOURCES', 'SECURITY', 'SUBSYSTEM', 'BOOTSTRAP', 'BROADCAST', 'EXECUTION', 'JAVASCRIPT'],
    10: ['BACKGROUND', 'CONNECTION', 'DEPLOYMENT', 'ENCRYPTION', 'EXPRESSION', 'FOUNDATION', 'IMPLEMENT', 'INTEGRATION', 'MANAGEMENT', 'MONITORING', 'PROCESSING', 'PRODUCTION', 'PROTECTION', 'REPOSITORY', 'RESOLUTION', 'STATISTICS', 'TECHNOLOGY', 'TERMINATOR', 'VALIDATION', 'PERMISSION'],
    11: ['APPLICATION', 'ARCHITECTURE', 'CONFIGURATION', 'DEVELOPMENT', 'ENVIRONMENT', 'INFORMATION', 'INSTALLATION', 'MAINTENANCE', 'PERFORMANCE', 'PROGRAMMING', 'TRANSACTION', 'TRANSMISSION', 'UTILIZATION', 'VERIFICATION', 'AUTHENTICATION'],
    12: ['ADMINISTRATION', 'COMMUNICATION', 'IMPLEMENTATION', 'INFRASTRUCTURE', 'ORGANIZATION', 'REGISTRATION', 'REQUIREMENTS', 'SPECIFICATION', 'SUBSCRIPTION', 'TRANSMISSION', 'VERIFICATION', 'CONFIGURATION'],
  },
};

/** @deprecated use getWordList */
export const WORD_LIST = WORD_LISTS.en;

export function normalizeGameLanguage(lang?: string): GameLanguage {
  return lang === 'it' ? 'it' : 'en';
}

export function getWordList(language: GameLanguage | string | undefined, length: number): string[] {
  const lang = normalizeGameLanguage(language);
  return WORD_LISTS[lang][length] ?? WORD_LISTS[lang][8] ?? WORD_LISTS.en[8];
}
